baseurl = "https://secure-brigade.com/"
languageCode = "ja"
title = "セキュア旅団"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# disqusShortname = "securebrigate"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
# hasCJKLanguage = true

[taxonomies]
tag = "tags"

# [permalinks]
# 	page = "/:filename/"
# 	about = "/:filename/"
# 	episode = "/:filename/"

[params]
	# General information
	author = "ken5scal"
	description = "セキュア旅団のページ説明"
	copyright = "Released under the MIT license"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/ken5scal/secure-brigate-blog"

	#version = "1.0.0"
	logo = "images/logo0.png"
	favicon = ""
	mdeia_prefix = "audio/"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
        primary = "indigo"
        accent  = "amber"

    [params.font]
        text = "Ubuntu"
        code = "Ubuntu Mono"

[social]
    twitter = "ken5scal"
    github  = "ken5scal"
    # email   = "kengoscal@gmail.com"

[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Podcast"
	url    = "podcast/"
	weight = 20

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
